services:

###################  RabbitMQ Cluster ###################
  rabbitmq-1:
    extends:
      file: files/docker-compose/rabbitmq.yaml
      service: rabbitmq
    hostname: rabbitmq-1
    volumes:
      - rabbitmq-1-data:/var/lib/rabbitmq/
      - rabbitmq-1-logs:/var/log/rabbitmq
    networks:
      - rabbitmq

  rabbitmq-2:
    extends:
      file: files/docker-compose/rabbitmq.yaml
      service: rabbitmq
    hostname: rabbitmq-2
    depends_on:
      - rabbitmq-1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq-1
    volumes:
      - rabbitmq-2-data:/var/lib/rabbitmq/
      - rabbitmq-2-logs:/var/log/rabbitmq
    networks:
      - rabbitmq

  rabbitmq-3:
    extends:
      file: files/docker-compose/rabbitmq.yaml
      service: rabbitmq
    hostname: rabbitmq-3
    depends_on:
      - rabbitmq-1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq-1
    volumes:
      - rabbitmq-3-data:/var/lib/rabbitmq/
      - rabbitmq-3-logs:/var/log/rabbitmq
    networks:
      - rabbitmq

################### Monitoring ###################
  grafana:
    extends:
      file: files/docker-compose/monitoring.yaml
      service: grafana
    networks:
      - "rabbitmq"
    volumes:          
      - grafana-data:/var/lib/grafana

  prometheus:
    extends:
      file: files/docker-compose/monitoring.yaml
      service: prometheus
    networks:
      - "rabbitmq"
    volumes:
      - prometheus-data:/prometheus

################### Proxy ###################
  haproxy:
    image: haproxy:3.1.0
    volumes:
      - ./files/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq-1
      - rabbitmq-2
      - rabbitmq-3
      - grafana
      - prometheus
    ports:
      - 15692:15692
      - 15672:15672
      - 5672:5672
      - 5552:5552
      - 3000:3000
      - 9090:9090
    networks:
      rabbitmq:
        aliases:
          - rabbitmq-cluster

networks:
  rabbitmq:

volumes:
  rabbitmq-1-data:
  rabbitmq-1-logs:
  rabbitmq-2-data:
  rabbitmq-2-logs:
  rabbitmq-3-data:
  rabbitmq-3-logs:
  grafana-data:
  prometheus-data:
