services:
  rabbitmq:
    image: rabbitmq:3.13.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_ERLANG_COOKIE=rabbitmq-test-cluster
    volumes:
     # - ./files/rabbitmq/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./files/rabbitmq/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh:ro
      - ./files/rabbitmq/rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./files/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    entrypoint: /usr/local/bin/cluster-entrypoint.sh